### ISSUE TITLE
JSVM library instead of application

### ISSUE THREAD

**Issue by rsommerard** [ntrrgc/jsvm#2]
JSVM is currently implemented as an Android application, what about make it as an Android library instead ? 🤔

**Comment by ntrrgc** [comment]
Yeah, this is completely on the roadmap. I just started out with an application to prototype without having to worry about packaging.

**Comment by ntrrgc** [comment]
@rsommerard I just finished this. Check the [README](https://github.com/ntrrgc/jsvm) to find how to download it from JitPack or the wiki to know [how to build it yourself](https://github.com/ntrrgc/jsvm/wiki/Building-JSVM).
